grafana:
    image: grafana/grafana:6.4.5
    ports:
        - "3000:3000"
    volumes:
        - ./:/var/lib/grafana/plugins/gapit-live_data-panel
        - ./provisioning:/etc/grafana/provisioning
    environment:
        - TERM=linux
